### ISSUE TITLE
Question about AlephNull example

### ISSUE THREAD

**Issue by potato4444** [LightAndLight/cbpv#1]
The `AlephNull` example `codata AlephNull where { next : AlephNull }` by name would seem to have countably many inhabitants. But is it not the Unit type, at least up to bisimilarity?

**Comment by LightAndLight** [comment]
Could you elaborate on your bisimilarity argument?

I'm not saying that AlephNull has countably infinite inhabitants (the type of Conaturals has that property). I'm saying that a value of type AlephNull has a countably infinite "size".

I think I understand where you're coming from. AlephNull is singly-inhabited. Maybe this would be clearer (up to massagings of Comp and Val):

```
codata Conat where { pred : F (Maybe (U Conat)) }

alephNull = {
  fix self : U Conat in 
  cocase { pred -> return[Just[rest]] }
}
```

**Comment by potato4444** [comment]
Bisimilarity for AlephNull would be this type (pseudo syntax, I don't know the exact features of cpbv):

    codata AlephNullBisim (x : AlephNull) (y : AlephNull) where { next : AlephNullBisim x y }

which can be inhabited for any x and y of type AlephNull:

    infinity = thunk[ fix self : U (AlephNullBisim x y) in cocase AlephNullBisim of { next -> force[self] } ]

So all values of type AlephNull are bisimilar.

---

The name AlephNull made me think it was going to be a type isomorphic to the naturals at first. I realised what it was once I read the definition, but it wasn't what I was expecting from the name.

**Comment by LightAndLight** [comment]
Cool I understand. Thanks for engaging with me on this :)
